### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by cliftonc** [Callidon/bloom-filters#1]
Thanks for making this library.

Is there any way to serialise the structures into something (e.g. json or a base64 encoded string) so that it can be persisted somewhere and re-instantiated?

**Comment by Callidon** [comment]
Thanks to you for using it ;)

Serialise structures can be sure be handy. I see how it can be done easily, so I will be working on it where I have a little spare time. 

I think that a support for serialisation into/from JSON should be enough, as if you have a JSON string, you can generate yourself the associated base64 encoded string.

**Comment by Callidon** [comment]
Added functionality for import/export from/to JSON with 9ee6c9cdd4796c76a6025260fa036bd3efc4658e

Usage:
```javascript
const BloomFilter = require('bloom-filters').BloomFilter;

const filter = new BloomFilter(15, 0.01);
filter.add('alice');

// export a bloom filter to JSON
const exported = filter.saveAsJSON();

// do something with the JSON object (save it as file, send it to a server, etc)
// ...

// import the same filter from its JSON export
const importedFilter = BloomFilter.fromJSON(exported);
console.log(filter.has('alice')); // output: true
console.log(filter.has('bob')); // output: false
```

This example has been added to the README

**Comment by cliftonc** [comment]
Perfect - thanks for the fast response!

**Comment by Callidon** [comment]
I've also updated the npm release from 0.4.1 to 0.5.0, don't forget to upgrade your dependencies! :octocat:
