### ISSUE TITLE
Exported JSON isn't portable

### ISSUE THREAD

**Issue by andrey-p** [Callidon/bloom-filters#2]
I was evaluating this library for a project I'm working on, where I need to export the bloom filter as a file, store it, then load it again from the file.

If I try using `saveAsJSON()`, the binary data is stored as an array of booleans, which, when saved to a file, looks like this:

```
[true, false, true, true, true, ...]
```

The bloom filter for a 25mb dataset ended up being ~120mb!

It would be nice to be able to save the file in a more space-efficient format.

**Comment by Callidon** [comment]
Hi,
Indeed, I noticed that the raw filter is stored as an array of boolean, which is pretty terrible when serialized into a JSON string. One easy solution is to use 0 and 1 to replace booleans, which will not require much work. I will fix this as soon as I have more spare time for this project (in about 2 weeks max I think).

Additionally,  I was also considering to use protocol buffers for a more efficient serialization format,
but I have not made any progress concerning that.

**Comment by Callidon** [comment]
Hi again,

I just published a new version of the package (v0.5.2) with 9cbc9afd303bc8a53b4f742c6700a62ad98d90be, which uses integers instead of boolean for coding bloom filters.
Can you please update your project and report the impact on your test dataset ?

**Comment by Callidon** [comment]
Issue closed due to the lack of reaction from the original author
