### ISSUE TITLE
Counting bloom filter

### ISSUE THREAD

**Issue by simone0893** [Callidon/bloom-filters#7]
Hello,

is there any chance that you could implement a counting bloom filter?
Would be great!

Thanks in advance!

**Comment by Callidon** [comment]
Hello

Yes, we could definitively implement a counting bloom filter. I could be a great addition to this library.
I will put this on our todo list, so we should have implemented it under a few weeks.

I will keep you updated!

**Comment by Callidon** [comment]
Hello again

Counting Bloom Filters have been implemented and released in v0.7.1 🎉 
The documentation is up to date and the README has been updated.
Feel free to report any bug/implementation mistakes if you find some!

Have fun :octocat:
