### ISSUE TITLE
Typescript types incompatible with recent versions of `@types/seedrandom`

### ISSUE THREAD

**Issue by richvdh** [Callidon/bloom-filters#72]
Since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63766, `seedrandom.State` is no longer a defined type; however `prng.state()` is still defined to return a `State`. Obviously, this causes a typescript error.

**Comment by folkvir** [comment]
Should be resolved with: https://github.com/Callidon/bloom-filters/releases/tag/v3.0.2
